README.md
This visualization helped me understand what was going on better than the lines of code in the existing example. Perhaps it's also worth mentioning in the readme that `OrderedDict` is what's returned from from `parse` and we're serializing to json because `pprint` does not work with OrderedDict.
=> Showing the structure of the resulting dict

tests/test_dicttoxml.py, xmltodict.py
This should solve the issue [Allow generators in input dicts for unparse() #91](https://github.com/martinblech/xmltodict/issues/91).
- a generator is also allowed (besides list and tuple) to represent node children in the `_emit()` function
- single root is checked inside the loop (with index taken eg. via `enumerate()`) - without the need for materializing the whole sequence
- a test is added that supplies an `OrderedDict` containing a generator to `unparse()`
=> Allow generators in input dicts for unparse() #91

README.md
Add description of using the cdata_key and attr_prefix to specify node properties and values. 
I found this part really confusing until I read the comments that were directly in the code; it would be nice if there were a description in the README.
=> Add description of cdata_key and attr_prefix to README

xmltodict.py
Original defused expat import was broken and not pointing to the location of defusedexpat's expat (pyexpat), raising the following error on parse:
"AttributeError: 'module' object has no attribute 'ParserCreate'"
=> Fixed defusedexpat expat import

tests/test_dicttoxml.py, xmltodict.py
short_empty_elements is introduced in Python 3.2.
set short_empty_elements to True, if we want single self-closed tags.
=> unparse: pass short_empty_elements to XMLGenerator

tests/test_xmltodict.py, xmltodict.py
This patch adds a default config to the parse function to turn off / disable DTDs / entity expansion / external entity fetching. It is the kind of thing defusedexpat does, except that defusedexpat modifies expat itself and make these features less catastrophic but still available.
The idea is, assuming these problematic features are not something that the casual XML parsing public require (including myself), and that similarly they won't investigate the optional defusedexpat parser dependency (as shown in PR 130), it would be OK to turn off this stuff by default. Users that require it can override this.
The approach taken is similar to that in the Django xml serializer [1], but this patch does not bother to raise errors when undesirable XML content is discarded.
A related issue is that …
=> Disable entities

xmltodict.py
Currently, `xmltodict` tries to determine whether its input is a file-like object by treating it as a file and, if that fails, treating it as a string.  However, if the input is a file but `item_callback` raises a `TypeError` or `AttributeError` for some reason of its own, the error will be discarded and replaced with the exception "`TypeError: must be string or read-only buffer, not file`", which is confusing and makes debugging harder.
This pull request makes `xmltodict` instead determine fileness by checking for the presence of a `read` attribute, which is the only method `xml.parsers.expat` needs.
=> Determine fileness by checking for `read` attribute

.travis.yml
`JYTHON=true` was only used once and excluded in all other cases.
`jython ez_setup.py` failed without causing the build to fail, see eg. https://travis-ci.org/martinblech/xmltodict/jobs/427429418#L487. When changing that to `$HOME/jython/bin/jython ez_setup.py` the next step (`easy_install nose`) failed.  After removing the command alltogether it worked.
This PR does *not* address `nose.plugins.cover: ERROR: Coverage not available: unable to import coverage module`.
=> Fix and simplify travis config

xmltodict.py
This allows the optional `force_list` parameter in `xmltodict.parse() ` to accept `True` as a valid input value which then allows to receive all text node values of an xml as lists, even if a node contains only a single child.
See my question in [#14](https://github.com/martinblech/xmltodict/issues/14#issuecomment-458893210) and the great answer of [candlerb](https://github.com/martinblech/xmltodict/issues/14#issuecomment-458899357).
=> Allow force_list=True for getting all keys as lists

tests/test_xmltodict.py, xmltodict.py
In my use case, I want to ignore all namespaces. I hoped I could do this by using a [defaultdict](https://docs.python.org/3.7/library/collections.html#collections.defaultdict) which returned `None` for all keys, but two minor issues in the code (see comments inline) prevented this from working as you would expect.
With this change, the following works:
```python
>>> import collections
>>> xml = """
... <root xmlns="http://defaultns.com/"
...       xmlns:a="http://a.com/"
...       xmlns:b="http://b.com/">
...   <x>1</x>
...   <a:y>2</a:y>
...   <b:z>3</b:z>
... </root>
... """
>>> namespaces = collections.defaultdict(lambda: None)
>>> xmltodict.parse(xml, process_namespaces=True, namespaces=namespaces) == {
...     'root': {
...         'x': '1',
...         'y': '2',
...         'z': …
```
=> Support defaultdict for namespace mapping

tests/test_xmltodict.py, xmltodict.py
* This can be useful to parse a request from the requests library using
iter_content().
* Also add a test to confirm that generator works.
I also found a problem with file-like objects where some data appears to get stuck in the internal buffer and doesn't get pushed out until more data comes in. This was a problem for us as we're streaming and want the callback to get called as soon as the close tag finishes (the server waits a bit after the close tag to send more data). I was able to work around this problem using the generators here.
=> parse(generator) is now possible

README.md, tests/test_dicttoxml.py, xmltodict.py
Add `expand_iter` kwarg to unparse that will expand lists into sets of XML elements rather than outputting the string representation of the list
This is more of a proposal than actual PR - I should probably update the README and add a test.  But before doing that I wanted to submit this.
Using a simple dict:
test_dict = {'root': {'imgs': ((1, 2), (3, 4))}}
Output before the change/with out the flag:
print(xmltodict.unparse(test_dict, pretty=True))
<?xml version="1.0" encoding="utf-8"?>
<root>
<imgs>(1, 2)</imgs>
<imgs>(3, 4)</imgs>
</root>
After:
print(xmltodict.unparse(test_dict, expand_iter="item", pretty=True))
<?xml version="1.0" encoding="utf-8"?>
<root>
<imgs>
<item>1</item>
<item>2</item>
</imgs>
<imgs>
<item>3</item>
<item>4</item>
</imgs>
</root>
=> Add expand_iter kw to unparse to expand iterables

xmltodict.py
=> Fix simple typo: precendence -> precedence

xmltodict.py
Fixes a DeepSource.io alert:
> Using the `len` function to check if a sequence is empty is not idiomatic and can be less performant than checking the truthiness of the object.
> 
> `len` doesn't know the context in which it is called, so if computing the length means traversing the entire sequence, it must; it doesn't know that the result is just being compared to 0. Computing the boolean value can stop after it sees the first element, regardless of how long the sequence actually is.
Not an actual issue here - just trying to avoid alerts from automated reviewing tools.
=> Do not use `len()` to determine if a sequence is empty

setup.py
With python3, the built-in `open()` function opens files in "text" mode by default (i.e. the `f.read()` method reads bytes and tries to decode them to unicode using the interpreter default encoding). Depending on the system locale, this default encoding may be `'ascii'`. Which leads to the following error:
```
~$ python3 setup.py egg_info
Traceback (most recent call last):
File "setup.py", line 12, in <module>
long_description = f.read()
File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2587: ordinal not in range(128)
```
The character at position 2587 is `ô` (from `Fantômas`) and is utf-8 encoded.
Force to open the file in "binary" mode (which is the only …
=> Fix UnicodeDecodeError with python3 and no utf-8 locale installed

xmltodict.py
#183 attributes not appearing in parse output even with xml_attribs = True
```
body ='''<api>
<cons id="79550" modified_dt="1526652449">
<firstname>Mackenzie</firstname>
</cons>
<cons id="79551" modified_dt="1526652549">
<firstname>Joe</firstname>
</cons>
<api>'''
items = []
def handler(path, item):
items.append(item)
xmltodict.parse(body, item_depth=2, item_callback=handler)
Results:
items = [
{
'@id': '79550',
'@modified_dt': '1526652449',
'firstname': 'Mackenzie',
},
{
'@id': '79551',
'@modified_dt': '1526652549',
'firstname': 'Joe',
}
]```
=> fix attributes not appearing in streaming mode

README.md
The README file did not mention anything about `conda` installation of `xmltodict`. This pull-request adds that information to the README file.
=> added conda installation command

tests/test_xmltodict.py, xmltodict.py
This PR should address #264 
I think `xmltodict` has been improperly handling significant whitespace by default when `strip_whitespace=True`. If the whitespace is part of a leaf node, it should be preserved, whereas whitespace elsewhere in the document can be safely removed. I also adjusted some of the existing tests to reflect this change. [This page](http://usingxml.com/Basics/XmlSpace) illustrates the difference.
=> Ensure significant whitespace is not trimmed

tests/test_dicttoxml.py, xmltodict.py
Originally `unparse(mydict, pretty=True, indent=2)` would fail with confusing error message,
as it only supported `unparse(mydict, pretty=True, indent='  ')`
This is not documented and prone to confusion, especially because there is a code snippet using int `indent` excerpted from [README.md](https://github.com/martinblech/xmltodict/blob/9c2b733/README.md#xmltodict).
```python
>>> print(json.dumps(xmltodict.parse("""
...  <mydocument has="an attribute">
...    <and>
...      <many>elements</many>
...      <many>more elements</many>
...    </and>
...    <plus a="complex">
...      element as well
...    </plus>
...  </mydocument>
...  """), indent=4))
{
"mydocument": {
"@has": "an attribute", 
"and": {
"many": [
"elements", 
"more elements"
]
}, 
"plus": {
"@a": "complex", 
"#text": …
```
=> Support indent by number

ez_setup.py
`BadZipfile` (with a small `f`) has been deprecated since Python 3.2, use `BadZipFile` (big `F`) instead, added in 3.2.
* https://docs.python.org/3/library/zipfile.html#zipfile.BadZipfile
* https://github.com/python/cpython/issues/86437
=> Replace deprecated BadZipfile with BadZipFile

xmltodict.py
In the past defusedexpat would protect against certain classes of XML attacks, but defusedexpat is no longer maintained.
A followup project defusedxml exists, but it is no longer needed. The types of vulnerabilities that defusedexpat/defusedxml prevented are already mitigated by fixes within expat itself and newer python versions. See discussion in issue #321 for details.
=> Remove defusedexpat import.

ez_setup.py
RUF027 Possible f-string without an `f` prefix
=> Apply ruff rule RUF027

xmltodict.py
RSE102 Unnecessary parentheses on raised exception
=> Apply ruff/flake8-raise rule RSE102

xmltodict.py
E721 Do not compare types, use `isinstance()`
=> Apply ruff/pycodestyle rule E721

xmltodict.py
=> Get rid of Python 2 basestring and unicode

ez_setup.py, tests/test_dicttoxml.py, tests/test_xmltodict.py, xmltodict.py
**⚠** f-strings were introduced in **Python 3.6**. Do you really want to keep Python 3.4 compatibility?
=> Apply ruff/pyupgrade rules (UP)

tests/test_xmltodict.py, xmltodict.py
Reverts martinblech/xmltodict#267. This is causing downstream issues (#361).
=> Revert "Ensure significant whitespace is not trimmed"
